version: 2

go-image: &go-image quay.io/deis/lightweight-docker-go:v0.3.0

base-go-job: &base-go-job
  docker:
    - image: *go-image
  environment:
    SKIP_DOCKER: true
  working_directory: /go/src/github.com/krancour/go-parrot

jobs:
  lint:
    <<: *base-go-job
    steps:
      - checkout
      - run:
          name: Lint Go Code
          command: make lint
  test:
    <<: *base-go-job
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: make test

workflows:
  version: 2
  lint-and-test:
    jobs:
      - lint
      - test